services:
    - type: web
      runtime: node
      name: tapp-payment-callback-server-1
      repo: https://github.com/pkhalladin/Tapp.PaymentCallbackServer
      plan: free
      buildCommand: npm install
      startCommand: npm start
